name: flutter_structure
description: "A comprehensive Flutter project template with clean architecture and bloc state management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1
  
  # State Management - Bloc
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  
  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.4.4
  
  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.5
  
  # Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+2
  
  # Navigation & Routing
  go_router: ^14.2.7
  
  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  
  # Date & Time
  intl: ^0.20.2
  
  # Device Features
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  
  # Location Services
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  
  # Media & Files
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  cached_network_image: ^3.4.1
  
  # Authentication & Security
  local_auth: ^2.3.0
  crypto: ^3.0.5
  
  # Analytics & Monitoring
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Payments
  # stripe_payment: ^1.1.4  # Uncomment when needed
  
  # Charts & Visualization
  fl_chart: ^0.69.0
  
  # HTTP Client
  http: ^1.2.2
  
  # Logging
  logger: ^2.4.0
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0
  
  # UI Components
  shimmer: ^3.0.0
  lottie: ^3.1.2
  
  # Internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting & Analysis
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - .env
  
  # Fonts
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

# Generate localization files
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
